import type { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck, EyeOff, ServerOff, Lock } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy - Your Photos Never Leave Your Device",
  description:
    "BgRemove processes images entirely in your browser. We don't upload, store, or analyze your photos. Read our straight-talk privacy policy.",
  alternates: { canonical: `${SITE.url}/privacy` },
};

const PROMISES = [
  { Icon: ServerOff, title: "Your images never reach our servers", body: "All AI processing happens in your browser using local memory and your CPU/GPU. There is no upload step." },
  { Icon: EyeOff, title: "We don't see your photos", body: "We physically cannot — the technical architecture makes it impossible. We didn't add a privacy mode; the only mode is private." },
  { Icon: Lock, title: "No image storage", body: "Even temporarily. The AI model loads from a CDN once and runs locally afterward." },
  { Icon: ShieldCheck, title: "No account required", body: "Because there's no need for one. There's nothing to log in to, nothing to sync, nothing to forget to delete." },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHeader
        eyebrow="Privacy"
        title="Your photos stay on your device. Period."
        description="Most “privacy-friendly” tools say they delete your photos after processing. BgRemove never receives them in the first place."
      />
      <section className="container py-10">
        <div className="grid gap-4 sm:grid-cols-2">
          {PROMISES.map(({ Icon, title, body }) => (
            <div key={title} className="rounded-xl border border-primary/30 bg-card p-5">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Icon className="h-5 w-5" />
              </div>
              <h2 className="mt-3 text-lg font-semibold">{title}</h2>
              <p className="mt-1.5 text-sm text-muted-foreground">{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="container py-10">
        <div className="prose prose-slate max-w-none dark:prose-invert">
          <h2>The technical version</h2>
          <p>
            When you visit {SITE.domain}, your browser downloads the BgRemove web app
            (HTML, CSS, JavaScript) along with a small AI model (~4 MB) from a public CDN.
            The model is cached locally after the first visit. When you select an image:
          </p>
          <ol>
            <li>The image is read into your browser&apos;s memory as a binary blob.</li>
            <li>It is decoded into pixel data inside an HTML <code>&lt;canvas&gt;</code> element.</li>
            <li>The local AI model runs inference on those pixels using WebAssembly + GPU acceleration.</li>
            <li>The output PNG is generated by the same canvas and offered as a download.</li>
            <li>When you close the tab, the image and result are released from memory. Nothing persists.</li>
          </ol>
          <p>
            <strong>No network request carries your image data.</strong> You can verify this yourself:
            open browser DevTools → Network tab, drop an image into BgRemove, and watch — no upload occurs.
          </p>

          <h2>What we do collect</h2>
          <ul>
            <li>
              <strong>Anonymous analytics</strong> (page views, browser type, country) via Google
              Analytics 4. We do not collect IP addresses in identifiable form.
            </li>
            <li>
              <strong>Standard server logs</strong> from our static host (Cloudflare Pages) for the
              HTML/JS/model files you download. These contain IP addresses and User-Agent strings,
              held according to Cloudflare&apos;s default retention.
            </li>
            <li>
              <strong>No cookies set by us</strong> aside from a theme preference (light/dark) stored
              in localStorage on your own device.
            </li>
          </ul>

          <h2>Third-party services</h2>
          <ul>
            <li>
              <strong>Google MediaPipe model + WASM runtime</strong> — fetched from{" "}
              <code>storage.googleapis.com</code> and <code>cdn.jsdelivr.net</code> on first visit.
              Standard CDN logging applies.
            </li>
            <li>
              <strong>Google Analytics 4</strong> — once enabled, sets a <code>_ga</code> cookie used
              for anonymous traffic measurement.
            </li>
            <li>
              <strong>Google AdSense</strong> — if shown, may set advertising cookies. Subject to a
              cookie consent banner for EU/UK visitors.
            </li>
          </ul>

          <h2>Your rights</h2>
          <p>
            Since we don&apos;t collect personally identifiable information about your image content,
            there&apos;s nothing of yours for us to delete. For analytics, opt out with any standard
            browser tracking blocker, or enable &quot;Do Not Track&quot;.
          </p>

          <h2>Contact</h2>
          <p>
            Questions or concerns? Email{" "}
            <Link href={`mailto:${SITE.email}`}>{SITE.email}</Link>.
          </p>

          <p className="text-xs text-muted-foreground">
            Last updated: {new Date().toISOString().split("T")[0]}
          </p>
        </div>
      </section>
    </>
  );
}
